name: Actualizar Noticias Ciberseguridad

on:
  schedule:
    - cron: '30 12 * * 5' # Se ejecuta los viernes a las 12:30 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Instalar dependencias
        run: pip install feedparser deep-translator

      - name: Ejecutar script de noticias
        run: python noticias_sec.py

      - name: Guardar cambios y forzar actualización
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          # Si hay cambios, hace commit y fuerza el push
          git diff --quiet && git diff --staged --quiet || (git commit -m "docs: actualizacion automatica noticias" && git push --force)
